# Experiments with numpy
Since numpy is probably the most used library for machine learning, it makes sense to get to terms with it before attempting any machine learning projects let alone coding neural networks by scratch
Some examples and functions are taken from the videos but **almost all of them are compliant with most recent Numpy documentation and show how to do things the way developers want us to**

In [1]:
import numpy as np

In [284]:
a = np.array([1,2,3])
b = np.array([2,3,4])

### Generating random numbers

#### 1. Generating normal distribution

In [285]:
# Generate 5 numbers in NORMAL distribution
# Their mean is 0 and standard deviation is 1 (values approach these numbers as number of samples grows larger)
from numpy.random import default_rng
rng = default_rng()
vals = rng.standard_normal(size=10)
print(f'Generated the following values: {vals}')
print(f'Mean: {vals.mean()}')
print(f'Standard deviation: {vals.std()}')

Generated the following values: [ 1.21474849  0.32415033 -0.55194599 -0.47414816 -1.51741449  2.48325047
 -2.44421036  0.84181934 -2.07546317 -0.19359826]
Mean: -0.2392811791073855
Standard deviation: 1.4503284012701576


#### 2. Generating random integer

In [286]:
# This code is considered obsolete by numpy documentation
# BUT it's much shorter than the proposed version

# Pass in `endpoint` - max value
# Generates a positive integer
np.random.randint(10)

3

#### 3. Generating random float

In [287]:
# Pass in `endpoint` - max value
# Generates a positive integer
rng.random()

0.29298680094102125

#### 4. Generating random integers

In [288]:
np.random.default_rng().integers(low=0, high=10, size=3)

array([2, 1, 6], dtype=int64)

#### 5. Generating random matrices of specified dimension

In [289]:
np.random.rand(2,3)

array([[0.47275638, 0.34312846, 0.42893538],
       [0.65517461, 0.96530486, 0.46701301]])

#### 6. Generating matrices filled with specified number

In [290]:
# Create an array of zeros
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [328]:
# Create an array of 1s
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [329]:
# Create an array filled with specified number
np.full((2,1), 7.3)

array([[7.3],
       [7.3]])

In [330]:
# Create an identity matrix of specified dimension
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [334]:
# Generate a homogenous distribution between specified values
# Num param is the number of numbers to generate between specified values
# Values are equally spaced
znp.linspace(start=-10, stop=10, num=5)

array([-10.,  -5.,   0.,   5.,  10.])

### When multiplying vectors, the arrays are mutiplied elementwise

In [292]:
a * b

array([ 2,  6, 12])

### Dot product
Dot product **of vectors** is essentially the summation of the result of vector multiplication

In [293]:
print(f'Dot product: {np.dot(a, b)}')
print(f'Sum of vector multiplication: {(a * b).sum() }')

Dot product: 20
Sum of vector multiplication: 20


## Numpy arrays

In [294]:
# A vector
vector = np.array([1,2,3])

vector, vector.ndim, vector.shape

(array([1, 2, 3]), 1, (3,))

In [295]:
# A matrix
matrix = np.array([
    [1,2,3],
    [4,5,6],
    [5,6,7]
])

matrix, matrix.ndim, matrix.shape

(array([[1, 2, 3],
        [4, 5, 6],
        [5, 6, 7]]),
 2,
 (3, 3))

#### Array slices and indexing

In [296]:
# Accessing the array just like a list of lists works:
print(matrix[0][1])

# Accessing the array a more numpy way:
print(matrix[0, 1])

2
2


In [297]:
# Slices also work
# Here we take only the second (index 1) COLUMN throughout ALL rows
print(matrix[:, 1])

[2 5 6]


In [298]:
# Here we take the first element in the first and last row
print(matrix[0::2, 0])

[1 5]


In [299]:
# Note that slicing copies the object
matrix[:,:] is matrix

False

#### Other operations with ND-arrays

In [300]:
print('Matrix:', matrix, sep='\n')
# Transpose
print('Transposed:', matrix.T, sep='\n')

Matrix:
[[1 2 3]
 [4 5 6]
 [5 6 7]]
Transposed:
[[1 4 5]
 [2 5 6]
 [3 6 7]]


In [301]:
# Find the inverse
np.linalg.inv(matrix)

array([[-2.81474977e+14,  1.12589991e+15, -8.44424930e+14],
       [ 5.62949953e+14, -2.25179981e+15,  1.68884986e+15],
       [-2.81474977e+14,  1.12589991e+15, -8.44424930e+14]])

In [302]:
# Find the determinant
np.linalg.det(matrix)

3.552713678800486e-15

In [303]:
# Get the diagonal
np.diag(matrix)

array([1, 5, 7])

In [304]:
# If we send a vector to `diag` function, it will create a matrix where every element except for the diagonal is 0
np.diag(np.diag(matrix))

array([[1, 0, 0],
       [0, 5, 0],
       [0, 0, 7]])

In [305]:
# Boolean indexing
# Returns a matrix of the same shape filled with bools
matrix > 5

array([[False, False, False],
       [False, False,  True],
       [False,  True,  True]])

In [306]:
# Get a 1D array of all elements matching the specified condition
matrix[matrix > 5]

array([6, 6, 7])

In [307]:
# Returns array OF THE SAME dimensions where elements satisfying the condition are kept (prop a) and
# other values are replaced by -1
np.where(matrix > 2, matrix, -1)

array([[-1, -1,  3],
       [ 4,  5,  6],
       [ 5,  6,  7]])

In [308]:
m2 = np.array([
    [-5, 1, 0],
    [2, 3, -9],
    [7, 0, 0]
])

# Replace all elements less or equal to zero with zero
np.where(m2 <= 0, 0, m2)

array([[0, 1, 0],
       [2, 3, 0],
       [7, 0, 0]])

In [309]:
# Same as above
m2[m2 <= 0] = 0

In [310]:
# Fancy indexing
a = np.array([1,2,3,4,5])
b = [1,2,3]
# Extracts elements with indeces specified in `b`
a[b]

array([2, 3, 4])

#### Working with indices

In [311]:
# Returns an array of indices of elements matching the condition
np.argwhere(a%2==0)

array([[1],
       [3]], dtype=int64)

In [312]:
a[np.argwhere(a%2==0)]

array([[2],
       [4]])

In [313]:
# Same but returns flattened list
np.argwhere(a%2==0).flatten()

array([1, 3], dtype=int64)

In [314]:
a[np.argwhere(a%2==0).flatten()]

array([2, 4])

#### Generating a list of numbers

In [315]:
np.arange(1, 3)

array([1, 2])

#### Reshaping

In [316]:
# Suppose we have a list of numbers
a = np.arange(1, 10)
print(a)
print('Shape:', a.shape)
print('# of dimensions:', a.ndim)

[1 2 3 4 5 6 7 8 9]
Shape: (9,)
# of dimensions: 1


In [317]:
# Now reshape so it's 3x3
b = a.reshape((3,3))
print(b)
print('Shape:', b.shape)
print('# of dimensions:', b.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
# of dimensions: 2


#### Adding dimensions

In [318]:
a = np.arange(1, 10)
print('Before reshaping:', a)
print('Shape:', b.shape)
print('# of dimensions:', b.ndim)
print()
# Add new axis
b = a[np.newaxis, :]
print('Add new horizontal axis', b)
print('Shape:', b.shape)
print('# of dimensions:', b.ndim)
print()
b = a[:, np.newaxis]
print('Add new vertical axis\n', b)
print('Shape:', b.shape)
print('# of dimensions:', b.ndim)

Before reshaping: [1 2 3 4 5 6 7 8 9]
Shape: (3, 3)
# of dimensions: 2

Add new horizontal axis [[1 2 3 4 5 6 7 8 9]]
Shape: (1, 9)
# of dimensions: 2

Add new vertical axis
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
Shape: (9, 1)
# of dimensions: 2


In [319]:
# Computing the mean of the matrix and decreasing each element by it
ma = np.array([
    [1.9, 5.7, 3.9],
    [3.3, 2.1, 1],
    [1.1, 3.2, 3.2]
])

print('Mean:', ma.mean())
ma -= ma.mean()
print('Modified matrix:\n', ma)

threshold = 0.7

print('Indices of elements whose absolute value is NOT within the threshold: \n', np.argwhere(abs(ma) > threshold))

Mean: 2.822222222222222
Modified matrix:
 [[-0.92222222  2.87777778  1.07777778]
 [ 0.47777778 -0.72222222 -1.82222222]
 [-1.72222222  0.37777778  0.37777778]]
Indices of elements whose absolute value is NOT within the threshold: 
 [[0 0]
 [0 1]
 [0 2]
 [1 1]
 [1 2]
 [2 0]]


#### Concatenating arrays

In [320]:
a = np.array([
    [1,2,3],
    [0,0,0]
])

b = np.array([
    [5,6,7],
    [1,1,1]
])

print('Concatenating along axis 0 (as rows):\n', np.concatenate((a,b), axis=0))
print()
print('Concatenating along axis 1 (as columns):\n', np.concatenate((a,b), axis=1))

Concatenating along axis 0 (as rows):
 [[1 2 3]
 [0 0 0]
 [5 6 7]
 [1 1 1]]

Concatenating along axis 1 (as columns):
 [[1 2 3 5 6 7]
 [0 0 0 1 1 1]]


In [321]:
# Stacking arrays
print('HStack:\n', np.hstack((a, b))) # Same as concatenating columns
print()
print('VStack:\n', np.vstack((a,b))) # Same as concatenating rows

HStack:
 [[1 2 3 5 6 7]
 [0 0 0 1 1 1]]

VStack:
 [[1 2 3]
 [0 0 0]
 [5 6 7]
 [1 1 1]]


#### Datascience functions

In [322]:
a = np.array([
    [1,0,1],
    [1,5,6],
    [1,8,9]
])
a

array([[1, 0, 1],
       [1, 5, 6],
       [1, 8, 9]])

In [323]:
a.sum() # Sum all of the elements

32

In [324]:
a.sum(axis=1) # Sum elements in rows

array([ 2, 12, 18])

In [325]:
a.sum(axis=0) # Sum elements in columns

array([ 3, 13, 16])

In [326]:
# Variance along columns
a.var(axis=0)

array([ 0.        , 10.88888889, 10.88888889])

In [327]:
# Standard deviation along rows
a.std(axis=1)

array([0.47140452, 2.1602469 , 3.55902608])

### About dot product

In [8]:
"""
If a is an N-D array and b is a 1-D array, it is a sum product over the last axis of a and b.

If a is an N-D array and b is an M-D array (where M>=2), it is a sum product
over the last axis of a and the second-to-last axis of b
"""
inputs = np.array([
    [1., -2., 3.],
    [-1., 2., -3.],
])

d_relu=np.array([
    [6.]
])

# We were calculating dweights - the derivative of activation function w.r.t. inputs.
# If we have multiple inputs for current neuron we expect to see them as rows in our matrix

# The derivative is calculated by multiplying each input by derivatives of the activation function OF EACH INPUT


ReLU function derivative returns 1 or 0 for each sum, so it returns a np.array with `n` rows and 1 column for `n` inputs. When we multiply it by the `dvalues` we get the following array as the value of `d_relu`:
```Python
[[6.]
 [0.]]
```
Each row corresponds to an input entry. Thus, to get the product of 